# Generated by Django 3.0.7 on 2020-07-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
        ('motivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='motivos.Motivo')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sedes.Sede')),
            ],
        ),
    ]
