# Generated by Django 3.0.7 on 2020-07-25 15:43

import consolidacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidacionFileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=consolidacion.models.upload_to)),
            ],
        ),
    ]
