# Generated by Django 3.0.7 on 2020-07-27 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200608_1630'),
        ('consolidacion', '0002_consolidacionfileuploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallConsolidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.IntegerField(unique=True)),
                ('cita_tall_id', models.IntegerField(null=True, unique=True)),
                ('cita_crm_id', models.IntegerField(null=True, unique=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('consolidacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consolidacion.Consolidacion')),
            ],
        ),
    ]
