# Generated by Django 3.0.7 on 2020-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidacion', '0004_remove_callconsolidacion_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='callconsolidacion',
            name='call_made',
            field=models.BooleanField(default=False),
        ),
    ]
