# Generated by Django 3.0.4 on 2020-03-31 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Modulo')),
                ('label', models.CharField(max_length=150, verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='App')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField(verbose_name='Estado')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Action')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.App'),
        ),
        migrations.AddConstraint(
            model_name='profilepermissions',
            constraint=models.UniqueConstraint(fields=('profile', 'action'), name='ProfileAction'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('app', 'name'), name='AppAction'),
        ),
    ]
