# Generated by Django 3.0.7 on 2020-10-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='App')),
                ('label', models.CharField(default='', max_length=100, verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del perfil')),
                ('active', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Modulo')),
                ('label', models.CharField(max_length=150, verbose_name='Etiqueta')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.App')),
            ],
            options={
                'unique_together': {('name', 'app')},
            },
        ),
        migrations.CreateModel(
            name='ProfilePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField(verbose_name='Estado')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Action')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'unique_together': {('profile', 'action')},
            },
        ),
    ]
