# Generated by Django 3.0.4 on 2020-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
    ]
