# Generated by Django 2.1.15 on 2020-06-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200601_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='profilepermissions',
            unique_together={('profile', 'action')},
        ),
    ]
