# Generated by Django 3.0.7 on 2020-10-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(error_messages={'unique': 'Ya existe un usuario registrado con este correo'}, max_length=254, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=255, verbose_name='Constraseña')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('active', models.BooleanField(verbose_name='Activo/Inactivo')),
                ('need_password', models.BooleanField(default=True, verbose_name='Cambiar contraseña')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('life', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperTecnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDeveloper')),
                ('tecnology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tecnology')),
            ],
            options={
                'unique_together': {('developer', 'tecnology')},
            },
        ),
    ]
