# Generated by Django 3.0.4 on 2020-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200322_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needPassword',
            field=models.BooleanField(default=True, verbose_name='Cambiar contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario registrado con este correo'}, max_length=254, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
