# Generated by Django 3.0.4 on 2020-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200529_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
