# Generated by Django 2.1.15 on 2020-06-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200601_0841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='developertecnologies',
            unique_together={('developer', 'tecnology')},
        ),
    ]
