# Generated by Django 3.0.7 on 2020-07-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200608_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
