# Generated by Django 3.0.4 on 2020-05-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginSession',
        ),
    ]
