# Generated by Django 3.0.7 on 2020-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('bodega_dms', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
