# Generated by Django 3.0.7 on 2020-07-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='bodega_dms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
