# Generated by Django 3.0.7 on 2020-07-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='form_creator.Form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(error_messages={'unique': 'Ya existe un formulario registrado con este nombre.'}, max_length=50, unique=True),
        ),
    ]
