# Generated by Django 3.0.7 on 2020-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0002_auto_20200713_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='asnwer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='question',
            field=models.TextField(),
        ),
    ]
