# Generated by Django 3.0.7 on 2020-10-31 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0003_auto_20200719_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollCampaing',
            new_name='PollCampaign',
        ),
        migrations.RenameField(
            model_name='questionanswers',
            old_name='campaing',
            new_name='campaign',
        ),
    ]
