# Generated by Django 3.0.7 on 2020-06-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200608_1630'),
        ('agent_console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConsoleOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=255, unique=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CedulaLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(blank=True, max_length=32, null=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'cedula_llamada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=1)),
                ('agent', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.IntegerField(unique=True)),
                ('fake', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', unique=True)),
            ],
        ),
    ]
