# Generated by Django 3.0.7 on 2020-07-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
        ('users', '0007_auto_20200608_1630'),
        ('agent_console', '0003_auto_20200621_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Sede')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', unique=True)),
            ],
        ),
    ]
