# Generated by Django 3.0.7 on 2020-06-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_console', '0003_cedulallamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=1)),
                ('agent', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
