# Generated by Django 3.0.7 on 2020-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_console', '0004_serverlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConsoleOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=255, unique=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
