# Generated by Django 3.0.7 on 2020-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_agent_audit_break_callattribute_callentry_callprogresslog_callrecording_calls_campaign_campaignentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.DeleteModel(
            name='CallAttribute',
        ),
        migrations.DeleteModel(
            name='CallEntry',
        ),
        migrations.DeleteModel(
            name='CallProgressLog',
        ),
        migrations.DeleteModel(
            name='CallRecording',
        ),
        migrations.DeleteModel(
            name='Calls',
        ),
        migrations.DeleteModel(
            name='CampaignExternalUrl',
        ),
        migrations.RemoveField(
            model_name='campaignform',
            name='id_campaign',
        ),
        migrations.RemoveField(
            model_name='campaignformentry',
            name='id_campaign',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='CurrentCallEntry',
        ),
        migrations.DeleteModel(
            name='CurrentCalls',
        ),
        migrations.DeleteModel(
            name='DontCall',
        ),
        migrations.DeleteModel(
            name='EccpAuthorizedClients',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='FormDataRecolected',
        ),
        migrations.DeleteModel(
            name='FormDataRecolectedEntry',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='QueueCallEntry',
        ),
        migrations.DeleteModel(
            name='ValorConfig',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignEntry',
        ),
        migrations.DeleteModel(
            name='CampaignForm',
        ),
        migrations.DeleteModel(
            name='CampaignFormEntry',
        ),
    ]
