# Generated by Django 3.0.7 on 2020-08-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200610_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
