# Generated by Django 3.0.7 on 2020-07-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_sede_bodega_dms'),
        ('asesores', '0002_asesor_asesor_dms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='sede',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='sedes.Sede'),
            preserve_default=False,
        ),
    ]
