# Generated by Django 3.0.7 on 2020-10-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_creator', '0003_auto_20200719_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type_campaign', models.IntegerField()),
                ('isabel_campaign', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='form_creator.Form')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tercero', models.IntegerField()),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignForm')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_creator.Answer')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.AnswersHeader')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_creator.Question')),
            ],
        ),
    ]
