# Generated by Django 3.0.7 on 2020-10-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20201024_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersheader',
            old_name='campaing',
            new_name='campaign',
        ),
    ]
